databases:
  - name: db-front
    host: 127.0.0.1
    port: 27017
    max_pool_size: 16
    ssl: false
  - name: bigchain-test
    host: 127.0.0.1
    port: 27018
    max_pool_size: 16
    ssl: false
  - name: bigchain-db-main
    host: 127.0.0.1
    port: 27019
    max_pool_size: 16
    ssl: false

caches:
  - name: api-cache
    host: 127.0.0.1
    port: 6379
    password:

applications:
  - name: front-app
    url: https://api.blockchainfue.com
    needle: BlockchainFUE Front API
  - name: write-api
    url: http://localhost:3000
    needle: Missing X-Public-Key header

smtp:
  host: mail.martianoids.com
  port: 25
  user: monitor@baes.es
  pass: Ein1ohpie9eige2s

admins:
  - name: Jorge Fuertes
    email: jorge@jorgefuertes.com
